apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neo4j-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: servers/server-2
    repoURL: https://github.com/GBrunelli/neo4j-argocd-cluster-template.git
    targetRevision: HEAD
