apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neo4j
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: servers
    repoURL: https://github.com/GBrunelli/neo4j-argocd-cluster-template.git
    targetRevision: HEAD
